name: Build Pull Request
on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-projects/spring-retry' }}
    steps:
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Check Out
        uses: actions/checkout@v4
      - name: Build
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: Print JVM Thread Dumps When Cancelled
        uses: ./.github/actions/print-jvm-thread-dumps
        if: cancelled()
